name: validate changes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.7

    - name: Restore dependencies
      run: nuget restore AdKatsLogger.sln

    - name: Build Solution
      run: msbuild.exe AdKatsLogger.sln /nologo /nr:false /p:platform="Any CPU" /p:configuration="Debug"

    - name: Run tests
      uses: microsoft/vstest-action@v1.0.0
      with:
        testAssembly: AdKatsLoggerTest.dll
        searchFolder: .\test\bin\Debug\
        runInParallel: true
